version: 1
disable_existing_loggers: true
formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(module)s - %(method)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
  file:
    class: logging.FileHandler
    filename: logs.log
    formatter: standard

root:
  level: INFO
  handlers: [console, file]